apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:YBHYSsM+obMq+1yn7Ux+NYd0Bgms7odW3g==,iv:8CjGLBUVuhH2lo75i2TOOWc9iXaprRvR8IJl7egumq4=,tag:10V7lr7AvXrqvi9Fe4qfQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-28T22:13:21Z"
    mac: ENC[AES256_GCM,data:68suIDsIZr6RxwzBJg1ZXKTp68Wf+CW4RjwDSg6GjhL28JRXJs5u3paHc55XV94X9FCUlz52MtWSXQwcXUe32YKFWliaXYIpjTvlxceaxTcygZEWRV3jzhYr7nlaDHAezfmn6iyRiuvrh+uSR0Nxi3ilZ3kAeioGzzpFwM4sGHU=,iv:AntXI+scQY74Ym+n/s/SZQF6ICDocxK6xM7CDIJm/XQ=,tag:Ze73Pv/SIfa8vgDfuQdcJg==,type:str]
    pgp:
        - created_at: "2026-01-28T22:13:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA7ufPcUH/kX/AQwAn+u/3x+HBZB9YWJkOI+ERWa9g23CKXxvojyH9bEYOERn
            0Ts3FhbXD+VdOG2zWqTfzunWsKZKau/QTpqn001HXC50fzVBB0FwQQ6Xcqcf7Nl3
            5Pu9qlm2f0DsxyLQ5kPbp9d9VE2dqAk8IbZAYokI5npZ94siZxK9QhrsNFPP20/8
            dN1M8+vc82w3af4Z/HJ7I5HJ9g+IrIGlrsmnpU+g+Py4z+ydvlOHxlWioosRYAF5
            3zYv/c1aobzRPvQU4b0KsUDBjumm0B9F8MkNmKSr7n1Y8r0ZnoqREFpmO8D4M774
            GSLar6TgEdO2d9JoZ3Vgestj+rFqamtmbagQyXr9fpAGeebMs/mr8W1gybhOz5X6
            kwin50KarjaXoddKku0qpHamBWXTTHC+h6UhFgnhib2+oiSv32c7DOtWVS4PJWwi
            PJyNfX6SQ5QKIbxQTYddLllVE1PyvyJ0plBuBjpfwqA0nRsZbquPqrkfsEcLoV5n
            XmTrELwqkVMtDVeZZwmq1GgBCQIQwcOgN8pd5AZzGj/cBbTrs4dP6dUNh8g65wHg
            PTQcwyK4WM8TsePjkKyxTzNJoevwDeo/GDlPrUQfGVsTAwMP885fy5VjLdsalCDO
            f8hprqRLQufXz9y4ZOp2FFHZOK6mqLEi+w==
            =Vzc1
            -----END PGP MESSAGE-----
          fp: 3B6A6B7A353A2BBE992651E576D3682B2EC97C9A
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
