apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:mv/kMGaPYAP5PDwbKkUBxjuXHpN3N0YkPg==,iv:vdGz4oQNO3GlwhRVGJeho8egakwWhuAKm7aTlexzPPY=,tag:swd78nLKSaLOwtXJOsiGlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-31T19:25:11Z"
    mac: ENC[AES256_GCM,data:KcW+2LMYyuHlcGj/tVJ4NLda/no6NVtZd5cgBl+Ca4ywGZuFluDfUbry4hIceTYXSHlXEdVnmOaO8MriN6Sw+5fxdnydMwy0OOFJHHB8gQ+ATjZAtlnsmuJKno43JzfYPv+quqJhjio8LLa2rvd7aCJCVAP4IpWRl0vHRwTsBfs=,iv:u0GNupzfvJgISqSiiOWzdtVz9ZGdWlsmzumKWAnlvwk=,tag:wl6pyWbOHOv4/EHr6z/85A==,type:str]
    pgp:
        - created_at: "2026-01-31T19:25:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA3JCEMjeIcnQAQwAvuosKoaPGusNFumKO+TYa6AkxnOMyrNOuAWfMWmTk/Qf
            9j/op9aU9kedQthoHkZU3X0NxFnp1thntTbsvvvaQDmZV5LjaLtOnuSzAxVeTXWt
            URbxlOFJztu72PDip/9GRj/61B53ovp6Mx/mOrBPx3IDaWRDnt0a6h59jGK4Kf51
            uIqsclKxQq5NDJ6WUyuIZQGy89UHzTRLXOFVJsUjUppB0BK6rXwL28Cm8zWiDolg
            7RSbWOy/uGLP0zDcy1C6vu1eNJMUMqWgsmLhebIZMmg7pAe76lmT1+GUIV9ABAjV
            yZlgrtalcAQnygnsacwLUJd9/v0au/ISar0qWUj7GPtSU212s+3cELJwwawUJ399
            lcGbt4jO9+GgF0Do5LqpFsIBOIfo9ZNfGFy+g8wQuelNhoU70mqQSVfJ+YOs8N8u
            NBsm1YqGWYN86o6pcQVfMSbJSeoRB4OmIDCdeyeGQerKrV0OXxA0hONauCnmrl78
            nGQJFkHxmVHhU7He0kct1FsBCQIQEaC1XD/j9jaechkd/9mMaqX8hziPvVpjHi5t
            AEFKjbZe5dnfN9rHgqNcbCVA4bfUESMbSuhVcEkRRxon8XyOgTe3DVtU2Wkn5xR+
            KS61MWNIyW3l2cBj
            =yFVP
            -----END PGP MESSAGE-----
          fp: 2B2937EF190FF105A36B55DE31198BF05A2DEB48
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
